/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_nativecrash_Test */

#ifndef _Included_com_example_nativecrash_Test
#define _Included_com_example_nativecrash_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_nativecrash_Test
 * Method:    initial
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_nativecrash_Test_initial
  (JNIEnv *, jclass);

/*
 * Class:     com_example_nativecrash_Test
 * Method:    crash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_nativecrash_Test_crash
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
